// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjdVsKZLhD1wWRqB4obIpoj_dW-bFQipk',
    appId: '1:658435232319:web:81f9582ee4e48b98fb1e8a',
    messagingSenderId: '658435232319',
    projectId: 'email-auth-5af2c',
    authDomain: 'email-auth-5af2c.firebaseapp.com',
    storageBucket: 'email-auth-5af2c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD55EQ9saCvuFA8nIS1VcdEJEqPsiTkTuU',
    appId: '1:658435232319:android:296fab51d95e04e1fb1e8a',
    messagingSenderId: '658435232319',
    projectId: 'email-auth-5af2c',
    storageBucket: 'email-auth-5af2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQOhJzp9MAJzo0NrMQPgrrXl76dbKGxQM',
    appId: '1:658435232319:ios:f8886a200bbbb9bdfb1e8a',
    messagingSenderId: '658435232319',
    projectId: 'email-auth-5af2c',
    storageBucket: 'email-auth-5af2c.appspot.com',
    iosClientId: '658435232319-abaf5onjjnearkb5sdn07detir3837h0.apps.googleusercontent.com',
    iosBundleId: 'com.example.emailAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQOhJzp9MAJzo0NrMQPgrrXl76dbKGxQM',
    appId: '1:658435232319:ios:e889b7cfcced0204fb1e8a',
    messagingSenderId: '658435232319',
    projectId: 'email-auth-5af2c',
    storageBucket: 'email-auth-5af2c.appspot.com',
    iosClientId: '658435232319-9u6blvacgq2ajp13skujrk857sgu0nta.apps.googleusercontent.com',
    iosBundleId: 'com.example.emailAuth.RunnerTests',
  );
}
